_jobs/2016-08-25-development-initiatives-python-developer.md
Thanks for posting this ad so quickly - just made some small copy edits!
=> Minor edits to Development Initiatives job

_data/committee-2016-17.yml
Linking to my linkedin profile
=> Updated Website Link (Aleena)

about.md
=> corrected su link

jobs.html
I've not touched Jekyll or ruby before, I'm just cargo culting this comment https://github.com/jekyll/jekyll/issues/2515#issuecomment-146208288, might want to give this a check first!
=> Display jobs in reverse chronological order.

_tutorials/ssh-into-snowy.md
* Add section listing how to connect to lab machines
* Add example SSH config at bottom
* Add additional resources section linking to IT resources
=> Add additional SSH information to `ssh-into-snowy.md`

about.md, pages/alumni/index.md, pages/alumni/tech-scene-in-various-cities.md, pages/alumni/uk-work-visas.md
Added pages under `/pages/alumni/`
=> Added alumni info pages

_posts/2017-10-18-git.markdown
This is a short git tutorial that I intend to provide to the MS50 students, but I thought CSS would be a good place to host it because (a) everyone can see it that way and (b) it's not blackboard.
=> git tutorial

_tutorials/git.markdown
Updated Git Tutorial to reflect changes to Github's Student Pack.
https://education.github.com/pack
=> Git Tutorial Update

_tutorials/ssh-into-snowy.md
*wks and users change
*windows X11 forwarding instructions
*NoMachine section added
=> Updated SSH tutorial.

_sass/_sections.scss
This has been bothering me for a loooong time
=> Add invisible border when nav links not hovered

Gemfile, Gemfile.lock, _config.yml, _data/committee-2011-12.yml, _data/committee-2012-13.yml, _data/committee-2013-14.yml, pages/halloffame.md
* Add committees from 2011-2014
* Fix Jekyll build on Windows
=> Add old committees to website

_layouts/event.html, _layouts/job.html, _sass/_articles.scss, _sass/_events.scss
Some of the multi-column page widths were too narrow so long text (e.g. emails were overflowing). Overall width made wider and RHS panel also increased in size.
Also changed formatting of <code> on tutorial pages
=> Minor style adjustments

_events/2021_09_20_virtual_pub_quiz.md, _events/2021_09_21_virtual_game_sesh.md, _events/2021_09_23_meet_comittee_pizza.md
**Added:**
- Virtual pub quiz
- Virtual game sesh
- In-person department fair
=> Event welcome week 2021

_events/2021_11_06_BAE_CTF.md
- No banner or Facebook event yet
=> Add BAE CTF

_events/2022_05_06_agm.md
There seems to be an error on the time because of DST. Changed the time to 5pm on the MD file so it shows the right time on the site.
=> DST error?

_companies/Google.md
Company url shouldn't be hashcode url.
=> Change Google URL

_events/2022-10-19-egm.md
=> new forms for egm

_companies/roku.md, _jobs/2022_10_28_roku_software_engineering.md, _jobs/2022_10_28_roku_specialised_tech.md, _jobs/2022_11_10_roku_data_engineer_intern.md
- Update application deadline (and add note about rolling deadline)
- Fix formatting
- Change logo URL to careers homepage
=> Fix Roku jobs

admin/index.html
NetlifyCMS has died; replace the admin panel with netlifycms instead
=> Replace with netlifycms with static cms

admin/config.yml
Adds:
- jobs
- company sponsorship terms
- tutorials
- pages
=> Add more collections to the CMS

_includes/company_logo.html, _includes/event_cards.html, _layouts/event.html, _sass/_events.scss
=> Fix image paths
